### ISSUE TITLE
Key Error with Numpy

### ISSUE THREAD

**Issue by robpot891** [philipperemy/stock-volatility-google-trends#1]
I'm trying to run this code but I keep getting:

Traceback (most recent call last):
  File "/Users/username/stock-volatility-google-trends/run_model.py", line 27, in <module>
    sigma_mean = d['tr_col_mean']
  File "/Users/username/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 237, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'tr_col_mean is not a file in the archive'

I tried running it in python 3.5 and 3.6 and I updated Numpy but doesnt work. Is it an issue with the .npz file missing a column? Thanks. Really cool repo!

**Comment by philipperemy** [comment]
Thanks for this input.

Probably it has something to do with the npz. You will have to update it.

The repo is not 100% yet functional. If you can make it work, please submit a PR. That will be highly appreciated :)
